kind: Pod
apiVersion: v1
metadata:
  name: limits
spec:
  containers:
  - name: nginx
    image: nginx
    resource:
      reqiests:
        cpu: 100m
        memory: 68MI
    limits:
      cpu: 120m
      memory: 100Mi